### ISSUE TITLE
NARPS model missing ?

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/model-zoo#39]
Maybe I did not look hard enough but it seems to have been removed.

https://github.com/bids-standard/model-zoo/commit/3dee48fa87ce0c74fe324fc9d6b96daa86e9aa7f

**Comment by jmumford** [comment]
This one? https://github.com/bids-standard/model-zoo/tree/main/model-zoo/exhibits/narps

**Comment by adelavega** [comment]
It's in there now
